[theme]
# Primary accent color for interactive elements
primaryColor = "#FFA421"

# Background color for the main content area
backgroundColor = "#1E1E1E"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#404040"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"